name: Build APK Only

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch: { }

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        flavor: [ default, termux ]

    steps:
    # 1. 检出代码（关键修改：添加了 submodules: recursive）
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0

    # 2. 设置 Java 环境
    - name: set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle

    # 3. 赋予脚本执行权限
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    # 4. 开始构建 (生成 Release 包)
    # 注意：如果没有配置签名文件，Gradle 默认生成的可能无法安装，或者需要签名
    # 如果构建报错提示签名问题，可以将 assembleRelease 改为 assembleDebug
    - name: Build APK for ${{ matrix.flavor }}
      run: ./gradlew app_flavor:${{ matrix.flavor }}:assembleRelease

    # 5. 直接上传构建好的 APK 到 Artifacts
    # 这里使用了通配符路径，防止因为文件夹改名找不到文件
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: AIDE-${{ matrix.flavor }}
        path: |
          **/build/outputs/apk/**/release/*.apk      id: get_version_info
      run: |
        TAG_VERSION_NAME=$(grep "val TAG_VERSION_NAME =" build.gradle.kts | awk '{print $4}' | tr -d '"')
        echo "TAG_VERSION_NAME=${TAG_VERSION_NAME}" >> $GITHUB_ENV

      # 重命名
    - name: Rename APK for ${{ matrix.flavor }}
      run: mv build/app_flavor-${{ matrix.flavor }}/outputs/apk/${{ matrix.flavor }}/release/app-${{ matrix.flavor }}-release.apk build/app/outputs/apk/${{ matrix.flavor }}/release/AIDE-${{ matrix.flavor }}.apk

    - name: Upload  APK
      uses: actions/upload-artifact@v4
      with:
        name: AIDE-${{ matrix.flavor }}.apk
        path: build/app/outputs/apk/${{ matrix.flavor }}/release/AIDE-${{ matrix.flavor }}.apk
    # 发布到 Release
    - name: Upload APK for ${{ matrix.flavor }} to GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        body_path: changlog/${{ env.TAG_VERSION_NAME }}/README.md
        tag_name: ${{ env.TAG_VERSION_NAME }}
        repository: Familyye/AIDE-Plus-AS1
        files: build/app/outputs/apk/${{ matrix.flavor }}/release/AIDE-${{ matrix.flavor }}.apk
        token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
